version: '3'

services:
  db:
    image: 'mysql:latest'
    container_name: 'sportApp_db'
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=sportApp_db
      - MYSQL_USER=sportApp_user
      - MYSQL_PASSWORD=pass1234
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./my-datavolume:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10
    restart: always
  backend-server:
    container_name: 'sportApp_springboot'
    build: ./
    ports:
      - "8080"
    links:
      - "db"
    depends_on:
      - "db"
    restart: always
  frontend:
    container_name: 'sportApp_angular'
    build: ../eventApp-Angular/
    links:
      - "backend-server"
    depends_on:
      - "backend-server"
    ports:
      - "80:80"
